package com.zeabay.pulse.hello;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.web.reactive.server.WebTestClient;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class HelloServiceIntegrationTest {

  @LocalServerPort private int port;

  private WebTestClient webTestClient;

  @BeforeEach
  void setUp() {
    this.webTestClient = WebTestClient.bindToServer().baseUrl("http://localhost:" + port).build();
  }

  @Test
  @DisplayName("Should return 200 OK and a traceId internally generated by TSID generator")
  void hello_shouldReturnOkAndTraceId() {
    webTestClient
        .get()
        .uri("/hello/hello")
        .exchange()
        .expectStatus()
        .isOk()
        .expectBody()
        .jsonPath("$.success")
        .isEqualTo(true)
        .jsonPath("$.data")
        .isEqualTo("hello world")
        .jsonPath("$.traceId")
        .isNotEmpty();
  }

  @Test
  @DisplayName("Should return 200 OK and map global validation failures correctly")
  void validateDemo_shouldReturnValidationErrorWhenQueryIsEmpty() {
    webTestClient
        .get()
        .uri("/hello/validate-demo")
        .exchange()
        .expectStatus()
        .isOk()
        .expectBody()
        .jsonPath("$.success")
        .isEqualTo(false)
        .jsonPath("$.error.code")
        .isEqualTo("VALIDATION_ERROR")
        .jsonPath("$.error.message")
        .isEqualTo("Query param 'q' is required")
        .jsonPath("$.error.validationErrors[0].field")
        .isEqualTo("q")
        .jsonPath("$.error.validationErrors[0].message")
        .isEqualTo("must not be blank")
        .jsonPath("$.traceId")
        .isNotEmpty();
  }

  @Test
  @DisplayName("Should use WebClient customizer to propagate traceId to downstream calls")
  void callSelf_shouldInjectTraceIdHeaderInWebClient() {
    webTestClient
        .get()
        .uri("/hello/call-self")
        .exchange()
        .expectStatus()
        .isOk()
        .expectBody()
        .jsonPath("$.success")
        .isEqualTo(true)
        .jsonPath("$.data.traceId")
        .isNotEmpty()
        .jsonPath("$.data.downstreamTraceId")
        .isNotEmpty()
        .jsonPath("$.traceId")
        .isNotEmpty()
        .consumeWith(
            result -> {
              String json = new String(result.getResponseBodyContent());
              String upstream = com.jayway.jsonpath.JsonPath.read(json, "$.data.traceId");
              String downstream =
                  com.jayway.jsonpath.JsonPath.read(json, "$.data.downstreamTraceId");
              assertThat(upstream).isEqualTo(downstream);
            });
  }
}
